name: GitHub Classroom Workflow
on:
  push:
    branches: [ "**" ]

permissions:
  checks: write
  actions: read
  contents: read
  pull-requests: read

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "C1-C7. Compilacion y Codigo"
        id: codigo
        continue-on-error: true
        run: |
          make clean && make
          ./calculadora | grep -q '3 \* 5    = 15'
          ! grep -q 'TODO' operaciones.c

      - name: "C9. Branch feature"
        id: c9
        continue-on-error: true
        run: git fetch --all --quiet && git branch -a | grep -i 'feature/mi-funcion'

      - name: "C11. Branch sugerencia"
        id: c11
        continue-on-error: true
        run: git fetch --all --quiet && git branch -a | grep -i 'sugerencia'

      - name: "Teoria"
        id: teoria
        continue-on-error: true
        run: grep -i 'RESPUESTA_P1=b' readme.md

      - name: Finalizar
        if: always()
        run: |
          echo "## Revision Finalizada" >> $GITHUB_STEP_SUMMARY
          echo "Si ves este mensaje, el archivo YAML ya no tiene errores de sintaxis." >> $GITHUB_STEP_SUMMARY